[program:messenger-consume-game-events]
command=php /app/bin/console messenger:consume game_events --limit=10 --time-limit=3600 --memory-limit=32M
numprocs=3
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
process_name=%(program_name)s_%(process_num)02d
